config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show]
  resources :redemption_cards, only: [:create, :new, :show, :index] do
    collection do
      get 'check_form'
      post 'check'
    end
  end
end

app/models/redemption_card.rb
class RedemptionCard < ActiveRecord::Base

  validates :card_code, :card_pin, presence: true
  validates :card_code, uniqueness: true
  validates :card_code, length: { is: 16 }
  validates :card_pin, length: { is: 4 }

  belongs_to :user

  def self.use!(user, code, pin)
    redemption_card = RedemptionCard.where(used_at: nil, card_code: code, card_pin: pin).first
    if redemption_card
      redemption_card.update! used_at: Time.now, user: user
      user.update! balance: user.balance + redemption_card.amount
      redemption_card
    else
      nil
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  after_initialize :ensure_session_token

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, :email, uniqueness: true

  has_many :redemption_cards

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end

end

app/controllers/redemption_cards_controller.rb
class RedemptionCardsController < ApplicationController

  def new
    @redemption_card = RedemptionCard.new(user_id: current_user.id)
  end

  def index
    @redemption_cards = RedemptionCard.all
  end

  def create
    @redemption_card = RedemptionCard.create(redemption_card_params)

    @current_user_balance = current_user.balance
    @current_user_balance += 20
    if (params[:redemption_card][:card_code].to_s.include?("symphonycrocks")) &&
      (params[:redemption_card][:card_pin] == "1234")


      redirect_to redemption_card_url(@redemption_card.id)
      flash.now[:success] = ["Congrats! You've redeemed your Card Gift!"]
    else
      flash.now[:errors] = ["Wrong code & pin combination!"]
      flash.now[:errors] += ["Please retry or contact our support."]
      render :new
    end
  end

  def show
    current_user.balance += 20
    @redemption_card = RedemptionCard.find(params[:id])
  end

  def check_form
    @last_used_redemption_cards = RedemptionCard.where.not(used_at: nil).order('used_at DESC').limit(4)
  end

  def check
    @redemption_card = RedemptionCard.use!(
      current_user,
      params[:redemption_card][:card_code],
      params[:redemption_card][:card_pin]
    )

    if @redemption_card.nil?
      flash[:errors] = ["Wrong code & pin combination!"]
      redirect_to check_form_redemption_cards_path
    end
  end

  private
  def redemption_card_params
    params.require(:redemption_card).permit(:card_code, :card_pin)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
      )

    if @user
      sign_in(@user)
      redirect_to check_form_redemption_cards_url
    else
      flash.now[:errors] = ["Invalid email or password."]
      render :new
    end

  end

  def destroy
    current_user.reset_session_token! unless current_user.nil?
    session[:session_token] = nil
    @current_user = {id: nil, email: nil}
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to check_form_redemption_cards_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :balance)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
      html = <<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
      HTML
      html.html_safe
    end

end

app/helpers/redemption_cards_helper.rb
module RedemptionCardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftCardRedemption</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,700|Roboto" media="screen" title="no title" charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/redemption_cards/check.html.erb
<nav class="logo-container">
  <img class="logo-center" src="http://res.cloudinary.com/codehunt/image/upload/c_scale,w_120/v1461658809/logo_ubhtk5.png" alt="The Atlantic" />
</nav>
<p class="login-as">
  You're logged in as: <%= current_user.email %>
</p>

<div class="validation-card-center">
  <h2>
    A Gift Card of $<%= @redemption_card.amount %> has been redeemed to <%= current_user.email %>
  </h2>
  <br>
  <h3>
    Your balance is now: $<%= current_user.balance %>
  </h3>
  <br>
  <i class="fa fa-check-circle fa-5x" aria-hidden="true"></i>
  <br>
  <br>
  <%= link_to "Got it!", check_form_redemption_cards_url, class: "validation-button-checked" %>
</div>

app/views/redemption_cards/check_form.html.erb
<nav class="logo-container">
  <img class="logo-center" src="http://res.cloudinary.com/codehunt/image/upload/c_scale,w_120/v1461658809/logo_ubhtk5.png" alt="The Atlantic" />
</nav>
<p class="login-as">
  You're logged in as: <%= current_user.email %>
</p>
<div class="redeem-page-wrapper">

  <div class="redeem-wrapper">


      <h2 class="redeem-title">Redeem your gift card!</h2>

      <!-- Error messages -->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <ul>
            <li class="flash-message-item"><%= error %></li>
          </ul>
        <% end %>
      <% elsif flash[:success]%>
          <% flash[:success].each do |notice| %>
            <ul>
              <li class="flash-message-item"><%= notice %></li>
            </ul>
          <% end %>
      <% end %>

      <form class="" action="/redemption_cards/check" method="post">
        <%= auth_token %>
        <input title='You must enter a 16 character code' pattern='.{16}' required class="input-field" type="text" name="redemption_card[card_code]" id="card-code" placeholder="Enter your 16 digits card code" value="<%= @redemption_card.nil? ? '' : "#{@redemption_card.card_code}"%>">
        <br>
        <br>
        <input title='You must enter 4 digits pin' pattern='\d{4}' required class="input-field" type="text" name="redemption_card[card_pin]" id="card-Pin" value="<%= @redemption_card.nil? ? '' : "#{@redemption_card.card_code}"%>" placeholder="Enter your 4 digits pin">
        <br>
        <br>
        <input class="submit-button" type="submit" value="Redeem!">
      </form>

  </div>

  <div class="balance-archive-wrapper">
    <p class="balance-area">
      Your balance is currently: $<%= current_user.balance %>
    </p>
    <div class="separator">
    </div>

    <p class="history-area">
      Your history:
    </p>

    <table class="archive-table">
      <tr class="archive-table-rows">
        <th class="archive-table-head"># Gift Card</th>
        <th class="archive-table-head">Date</th>
        <th class="archive-table-head">Receiver</th>
        <th class="archive-table-head">Amount</th>
      </tr>
      <% @last_used_redemption_cards.each do |c| %>
        <tr class="archive-table-rows">
          <th class="archive-table-cells"><%= c.card_code %></th>
          <th class="archive-table-cells"><%= c.used_at %></th>
          <th class="archive-table-cells"><%= c.user.email %></th>
          <th class="archive-table-cells"><%= c.amount %></th>
        </tr>
      <% end %>
    </table>

  </div>
</div>
<p class="redeem-footer">
  <%= link_to "Logout", session_url, method: :delete %>
</p>

app/views/redemption_cards/new.html.erb
<nav class="logo-container">
  <img class="logo-center" src="http://res.cloudinary.com/codehunt/image/upload/c_scale,w_120/v1461658809/logo_ubhtk5.png" alt="The Atlantic" />
</nav>
<p class="login-as">
  You're logged in as: <%= current_user.email %>
</p>
<div class="redeem-page-wrapper">

  <div class="redeem-wrapper">


      <h2 class="redeem-title">Redeem your gift card!</h2>

      <!-- Error messages -->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <ul>
            <li class="flash-message-item"><%= error %></li>
          </ul>
        <% end %>
      <% elsif flash[:success]%>
          <% flash[:success].each do |notice| %>
            <ul>
              <li class="flash-message-item"><%= notice %></li>
            </ul>
          <% end %>
      <% end %>

      <form class="" action="/redemption_cards" method="post">
        <%= auth_token %>
        <input class="input-field" type="text" name="redemption_card[card_code]" id="card-code" placeholder="Enter your 16 digits card code" value="<%= @redemption_card.nil? ? '' : "#{@redemption_card.card_code}"%>">
        <br>
        <br>
        <input class="input-field" type="text" name="redemption_card[card_pin]" id="card-Pin" value="<%= @redemption_card.nil? ? '' : "#{@redemption_card.card_code}"%>" placeholder="Enter your 4 digits pin">
        <br>
        <br>
        <input class="submit-button" type="submit" value="Redeem!">
      </form>

  </div>

  <div class="balance-archive-wrapper">
    <p class="balance-area">
      Your balance is currently: $<%= current_user.balance %>
    </p>
    <div class="separator">
    </div>

    <p class="history-area">
      Your history:
    </p>

    <table class="archive-table">
      <tr class="archive-table-rows">
        <th class="archive-table-head"># Gift Card</th>
        <th class="archive-table-head">Date</th>
        <th class="archive-table-head">Receiver</th>
        <th class="archive-table-head">Amount</th>
      </tr>
      <tr class="archive-table-rows">
        <td class="archive-table-cells">12987117239712</td>
        <td class="archive-table-cells">09/04/2016</td>
        <td class="archive-table-cells">azeiyo@oizued.com</td>
        <td class="archive-table-cells">$20</td>
      </tr>
      <tr class="archive-table-rows">
        <td class="archive-table-cells">97178162389712</td>
        <td class="archive-table-cells">04/28/2016</td>
        <td class="archive-table-cells">azeiyo@oizued.com</td>
        <td class="archive-table-cells">$40</td>
      </tr>
      <tr class="archive-table-rows">
        <td class="archive-table-cells">26987312409873</td>
        <td class="archive-table-cells">02/25/2016</td>
        <td class="archive-table-cells">azeiyo@oizued.com</td>
        <td class="archive-table-cells">$30</td>
      </tr>
    </table>

  </div>
</div>
<p class="redeem-footer">
  <%= link_to "Logout", session_url, method: :delete %>
</p>

app/views/redemption_cards/show.html.erb
<nav class="logo-container">
  <img class="logo-center" src="http://res.cloudinary.com/codehunt/image/upload/c_scale,w_120/v1461658809/logo_ubhtk5.png" alt="The Atlantic" />
</nav>
<p class="login-as">
  You're logged in as: <%= current_user.email %>
</p>
<p>
  A Gift Card of $20 has been redeemed to <%= current_user.email %>
</p>
<p>
  Your balance is now: <%= current_user.balance %>
</p>

<%= link_to "Got it!", new_redemption_card_url %>

app/views/users/new.html.erb
<div class="page-wrapper">

  <div class="brand-name">
    <img src="http://res.cloudinary.com/codehunt/image/upload/c_scale,w_120/v1461658809/logo_ubhtk5.png"
         alt="Logo" />
  </div>

  <div class="auth-wrapper">

      <h2 class="signup-title">Create an account</h2>

      <!-- Error messages -->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <ul>
            <li class="flash-message-item"><%= error %></li>
          </ul>
        <% end %>
      <% end %>

      <form class="auth-form" action="/users" method="post">
        <%= auth_token %>
        <input class="input-field"
               type="email"
               required
               name="user[email]"
               id="email"
               placeholder="Email"
               value="<%= @user.nil? ? '' : "#{@user.email}"%>"
               >
        <br>
        <br>
        <input class="input-field"
               type="password"
               name="user[password]"
               id="password"
               placeholder="Password">
        <br>
        <br>

        <input class="submit-button" type="submit" value="Sign Up">
      </form>
    </div>
    <br>
    <p class="auth-footer">
      Already have an account? <%= link_to "Sign In!", new_session_url %>
    </p>


</div>